package Controll;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabrieltaborda
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class BancoGUIPOO extends javax.swing.JFrame {
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    
    /**
     * Creates new form BancoGUIPOO
     */
    public BancoGUIPOO() {
        initComponents();
        lbGiro.setVisible(false);  //Oculta el label sobre giro
        txGiro.setVisible(false);  //Oculta el caja de texto sobre giro
       modelo = new DefaultTableModel();
       modelo.addColumn("CUENTA");
       modelo.addColumn("CLIENTE");
       modelo.addColumn("SALDO");
       modelo.addColumn("TIPO DE CUENTA");
       this.jTable1.setModel(modelo);
       
       modelo2 = new DefaultTableModel();
       modelo2.addColumn("CUENTA");
       modelo2.addColumn("CLIENTE");
       modelo2.addColumn("SALDO");
       modelo2.addColumn("TIPO DE CUENTA");
       this.jTable2.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brAhorro = new javax.swing.JRadioButton();
        brCorriente = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txNum = new javax.swing.JTextField();
        txNom = new javax.swing.JTextField();
        txSal = new javax.swing.JTextField();
        txCla = new javax.swing.JTextField();
        lbGiro = new javax.swing.JLabel();
        txGiro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        btRetornar = new javax.swing.JButton();
        btEliminarTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creacion de Cuenta");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PROGRAMA BANCO (gui y poo)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de Cuenta:");

        buttonGroup1.add(brAhorro);
        brAhorro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brAhorro.setSelected(true);
        brAhorro.setText("Cuenta de Ahorro");
        brAhorro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brAhorroStateChanged(evt);
            }
        });

        buttonGroup1.add(brCorriente);
        brCorriente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brCorriente.setText("Cuenta Corriente");
        brCorriente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                brCorrienteStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Numero de Cuenta:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Cliente: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Saldo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Clave:");

        lbGiro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbGiro.setText("Sobre Giro:");

        txGiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btBorrar.setText("Borrar Fila");
        btBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBorrarMouseClicked(evt);
            }
        });
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        btRetornar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRetornar.setText("Retornar");
        btRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRetornarMouseClicked(evt);
            }
        });

        btEliminarTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEliminarTodo.setText("Eliminar Todo");
        btEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarTodoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CUENTAS DE AHORRO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CUENTAS CORRIENTE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(brAhorro)
                                    .addGap(18, 18, 18)
                                    .addComponent(brCorriente))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(lbGiro))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txNom)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txSal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txCla, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txGiro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 151, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEliminarTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRetornar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brAhorro)
                    .addComponent(brCorriente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txCla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbGiro)
                    .addComponent(txGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btBorrar)
                    .addComponent(btEliminarTodo)
                    .addComponent(btRetornar))
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brCorrienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brCorrienteStateChanged
        // Evento cambio de estado de los boton de radio Corriente
         if(brAhorro.isSelected()){  //si esta seleccionado Ahorro, los oculta
            lbGiro.setVisible(false);
            txGiro.setVisible(false);
        }
         if(brCorriente.isSelected()){ //si esta seleccionado corriente, los muestra
            lbGiro.setVisible(true);
            txGiro.setVisible(true);
         }
    }//GEN-LAST:event_brCorrienteStateChanged

    private void brAhorroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_brAhorroStateChanged
        // Evento cambio de estado de los boton de radio Ahorro
        if(brAhorro.isSelected()){  //si esta seleccionado Ahorro, los oculta
            lbGiro.setVisible(false);
            txGiro.setVisible(false);
        }
         if(brCorriente.isSelected()){ //si esta seleccionado corriente, los muestra
            lbGiro.setVisible(true);
            txGiro.setVisible(true);
         }
    }//GEN-LAST:event_brAhorroStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        String []DatosCuentaAhorros =new String[4];
        String []DatosCuentaCorriente =new String[4];
        
         if(brAhorro.isSelected()){
            DatosCuentaAhorros[0]=txNum.getText();
            txNum.setText(null);
            DatosCuentaAhorros[1]=txNom.getText();
            txNom.setText(null);
            DatosCuentaAhorros[2]=txSal.getText();
            txSal.setText(null);
            DatosCuentaAhorros[3]=brAhorro.getText();
            brAhorro.setText(null);
            txCla.setText(null);
            modelo.addRow(DatosCuentaAhorros);
            JOptionPane.showMessageDialog(null, "CUENTA CREADA CON EXITO");
         }
          if(brCorriente.isSelected()){
            DatosCuentaAhorros[0]=txNum.getText();
            txNum.setText(null);
            DatosCuentaAhorros[1]=txNom.getText();
            txNom.setText(null);
            DatosCuentaAhorros[2]=txSal.getText();
            txSal.setText(null);
            DatosCuentaAhorros[3]=brCorriente.getText();
            brCorriente.setText(null);           
            txCla.setText(null);
            modelo2.addRow(DatosCuentaCorriente);
            JOptionPane.showMessageDialog(null, "CUENTA CREADA CON EXITO");
         }           
    }//GEN-LAST:event_jButton1MouseClicked

    private void btRetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRetornarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btRetornarMouseClicked

    private void btBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBorrarMouseClicked
        // TODO add your handling code here:
       int filaSeleccionada=jTable1.getSelectedRow();
       int filaSeleccionadaCorriente=jTable2.getSelectedRow();
       if(filaSeleccionada>=0){
           modelo.removeRow(filaSeleccionada);
       }else{
           JOptionPane.showMessageDialog(null, "Tabla vacia o no selecciono una fila");
       }
       if(filaSeleccionadaCorriente>=0){
           modelo2.removeRow(filaSeleccionadaCorriente);
       }else{
           JOptionPane.showMessageDialog(null, "Tabla vacia o no selecciono una fila");
       }
    }//GEN-LAST:event_btBorrarMouseClicked

    private void btEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarTodoActionPerformed
       int cantidadFilas = jTable1.getRowCount();
       int cantidadFila2 = jTable1.getRowCount();
       for(int i=cantidadFila2-1;i>=0;i--){
           modelo.removeRow(i);
       }
       for(int i=cantidadFilas-1;i>=0;i--){
           modelo2.removeRow(i);
       }
    }//GEN-LAST:event_btEliminarTodoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancoGUIPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancoGUIPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancoGUIPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancoGUIPOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancoGUIPOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton brAhorro;
    private javax.swing.JRadioButton brCorriente;
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btEliminarTodo;
    private javax.swing.JButton btRetornar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbGiro;
    private javax.swing.JTextField txCla;
    private javax.swing.JTextField txGiro;
    private javax.swing.JTextField txNom;
    private javax.swing.JTextField txNum;
    private javax.swing.JTextField txSal;
    // End of variables declaration//GEN-END:variables
}
